export const maxsulot = [
    {
        id:1,
        img:'',
        name:'Ortepedik Eko master',
        kg:150,
        yil:3,
        olcham: '200x120x40',
        sigim:2,
        malumot:'Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.',
        narx: 1699999,
    },
    {
        id:2,
        img:'',
        name:'Ortepedik Eko master',
        kg:150,
        yil:3,
        olcham: '200x120x40',
        sigim:2,
        malumot:'Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.',
        narx: 1699999,
    },
    {
        id:3,
        img:'',
        name:'Ortepedik Eko master',
        kg:150,
        yil:3,
        olcham: '200x120x40',
        sigim:2,
        malumot:'Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.',
        narx: 1699999,
    },
    {
        id:4,
        img:'',
        name:'Ortepedik Eko master',
        kg:150,
        yil:3,
        olcham: '200x120x40',
        sigim:2,
        malumot:'Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.',
        narx: 1699999,
    },
    {
        id:5,
        img:'',
        name:'Ortepedik Eko master',
        kg:150,
        yil:3,
        olcham: '200x120x40',
        sigim:2,
        malumot:'Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.',
        narx: 1699999,
    },
    {
        id:6,
        img:'',
        name:'Ortepedik Eko master',
        kg:150,
        yil:3,
        olcham: '200x120x40',
        sigim:2,
        malumot:'Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.',
        narx: 1699999,
    },
    {
        id:7,
        img:'',
        name:'Ortepedik Eko master',
        kg:150,
        yil:3,
        olcham: '200x120x40',
        sigim:2,
        malumot:'Penatibus viverra gravida rhoncus in. At turpis morbi ante tortor a est. Habitant adipiscing ut sed pulvinar tellus, ut urna, fermentum. Porttitor senectus lorem rhoncus facilisi ac dictum varius egestas.',
        narx: 1699999,
    },
]